server:
  port: 8090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onclass
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-u